name: "Default Agent"
description: "A general-purpose assistant agent"
model:
  provider: "ollama" # Can be 'openai', 'ollama', or others
  name: "phi4-mini" # Model name, e.g., 'gpt-4', 'llama3', etc.
  temperature: 0.7
  max_tokens: 1000
  top_p: 0.9
  
agent:
  persona: >
    You are a helpful assistant who provides accurate and concise information.
    You respond in a friendly, conversational manner.
  
  tools:
    - search
    - calculator

memory:
  type: "conversation_buffer"
  max_token_limit: 2000